### ISSUE TITLE
sending ocaml to REPL requires suffix ";;"

### ISSUE THREAD

**Issue by mostafatouny** [pappasam/nvim-repl#28]
Hello,
In ocaml, the code to be compiled differs from the one to be called in REPL. ocaml requires a suffix of `;;` for the REPL. See [this](https://ocaml.org/docs/toplevel-introduction) link or just read the quote:

> This # means it is waiting for input, so you can start writing your code after the prompt. To evaluate it, add a double semicolon ;; to signal the end of the expression and press Enter.

For example, a line `let () = print_endline "hello world"` should be translated to the REPL as `let () = print_endline "hello world";;` `

I hacked it by modifying `auto_reload/repl.vim`, where I added `let g:mySuffix = ";;"` at the beginning of the file,  and added `let buflines_chansend += [g:mySuffix]` inside `repl#sendblock` function.

![Screenshot_2024-12-13_10-25-31](https://github.com/user-attachments/assets/834b01bd-5444-46f7-a86a-27003829b04f)

it works even if I sent a cell with two lines, adding a single suffix `;;` for both.

maybe you want to add a native support for prefix and suffix, for each language. for example,
```
vim.g["repl_suffix"] = {
  ocaml = ";;"
}
```

**Comment by pappasam** [comment]
I like the idea of adding prefix and suffix options... let me think about the best way to add this feature.

**Comment by pappasam** [comment]
I think we'll need to modify how we specify repls themselves, since the addition of `;;` is more conceptually tied to a repl than to a language.

We'll need to rethink how `g:repl_filetype_commands` is structured

https://github.com/pappasam/nvim-repl/blob/286e6f5854c373d554b44ffd79023867d0d3ef08/plugin/repl.vim#L45-L53

and how it is parsed:

https://github.com/pappasam/nvim-repl/blob/286e6f5854c373d554b44ffd79023867d0d3ef08/autoload/repl.vim#L78-L86

**Comment by pappasam** [comment]
I'm not a big fan of the conda special case btw, so we don't need to bend over backwards to preserve it

**Comment by pappasam** [comment]
Resolved here: https://github.com/pappasam/nvim-repl/commit/ca2d5ae09f5f5a6fdd9c3d0fcd02ac54d0b4b1be
